CREATE TABLE IF NOT EXISTS employee (employee_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL,
employee_role VARCHAR(255) DEFAULT NOT NULL, employee_status VARCHAR(255) NOT NULL);

CREATE TABLE IF NOT EXISTS customer (phone_number LONG NOT NULL PRIMARY KEY,name VARCHAR(255) NOT NULL, street_address VARCHAR(255),
zip_code VARCHAR(255) NOT NULL);

CREATE TABLE IF NOT EXISTS product (product_id INT NOT NULL  AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL,
price DECIMAL , product_size VARCHAR(255) NOT NULL);

